version: '3'
services:
   postgres:
    image: postgres:13
    container_name: db_social_media
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: social_media
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Olimp123
