spring:
  application:
    name: profitsoft-unit-2

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/social_media
    username: postgres
    password: Olimp123
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/db.changelog/app-changelog.xml
    default-schema: public

# Server configuration
server:
  port: 8082
